import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { unzipSync, strFromU8 } from 'fflate';
import { openKeymapFixture } from './keymap-fixture';
import { navigateWorkspace } from './workspace-navigation';
import { readWorkspaceDocument } from './workspace-storage';

test('a switched encoder replaces a key without losing its layered press identity', async ({ page }) => {
  await openKeymapFixture(page);
  await page.getByRole('combobox', { name: 'Keycap profile for matrix' }).selectOption('dsa');
  await navigateWorkspace(page, 'Keymap');
  const panel = page.locator('.wb-keymap-panel');
  await page.getByRole('button', { name: 'Edit key SW1', exact: true }).click();
  await panel.getByLabel('SW1 behavior', { exact: true }).selectOption('mod-tap');
  await expect.poll(async () => (await readWorkspaceDocument(page)).keymap?.layers[0].bindings['matrix/matrix/r0c0']?.kind).toBe('mod-tap');
  await panel.getByRole('button', { name: 'Add layer', exact: true }).click();
  await panel.getByRole('group', { name: 'Keymap layers' }).getByRole('button', { name: '1 Layer 1' }).click();
  await panel.getByLabel('SW1 behavior', { exact: true }).selectOption('layer-tap');
  await panel.getByLabel('SW1 layer', { exact: true }).selectOption('base');
  await panel.getByLabel('SW1 tap', { exact: true }).fill('B');
  await panel.getByLabel('SW1 tap', { exact: true }).press('Tab');
  await expect.poll(async () => (await readWorkspaceDocument(page)).keymap?.layers[1].bindings['matrix/matrix/r0c0']).toEqual({ kind: 'layer-tap', layerId: 'base', tap: 'B' });
  await panel.getByRole('group', { name: 'Keymap layers' }).getByRole('button').first().click();
  const before = await readWorkspaceDocument(page);
  const key = before.parts.find(part => part.reference === 'SW1')!;
  await navigateWorkspace(page, 'Layout');
  await page.getByRole('button', { name: 'Select key, row 1, column 1', exact: true }).press('Enter');
  await page.getByLabel('Key Assembly', { exact: true }).selectOption('ergogen:ceoloide/rotary_encoder_ec11_ec12');
  await expect.poll(async () => (await readWorkspaceDocument(page)).parts.find(part => part.id === key.id)?.definitionId).toBe('ergogen:ceoloide/rotary_encoder_ec11_ec12');
  const replaced = await readWorkspaceDocument(page);
  expect(replaced.parts.find(part => part.id === key.id)?.pose).toEqual(key.pose);
  expect(replaced.keymap).toEqual(before.keymap);
  expect(replaced.keycaps).toEqual(before.keycaps);
  expect(replaced.layouts).toEqual(before.layouts);
  expect(replaced.matrices[0].partIds).toContain(key.id);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.getByLabel('Key Assembly', { exact: true })).toHaveValue(key.definitionId);
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect.poll(async () => (await readWorkspaceDocument(page)).parts.find(part => part.id === key.id)?.definitionId).toBe('ergogen:ceoloide/rotary_encoder_ec11_ec12');
  await page.reload();
  await navigateWorkspace(page, 'Keymap');
  await page.getByRole('button', { name: 'Edit key SW1', exact: true }).click();
  await expect(panel.getByLabel('SW1 behavior', { exact: true })).toHaveValue('mod-tap');
  await panel.getByRole('button', { name: 'Encoders', exact: true }).click();
  await panel.getByLabel('SW1 clockwise behavior', { exact: true }).selectOption('key-press');
  await panel.getByLabel('SW1 clockwise keycode', { exact: true }).fill('C_VOL_UP');
  await panel.getByLabel('SW1 clockwise keycode', { exact: true }).press('Tab');
  await panel.getByRole('group', { name: 'Keymap layers' }).getByRole('button', { name: '1 Layer 1' }).click();
  await panel.getByLabel('SW1 clockwise behavior', { exact: true }).selectOption('key-press');
  await panel.getByLabel('SW1 clockwise keycode', { exact: true }).fill('C_BRI_UP');
  await panel.getByLabel('SW1 clockwise keycode', { exact: true }).press('Tab');
  await expect.poll(async () => (await readWorkspaceDocument(page)).keymap?.layers[1].sensors[key.id]?.clockwise).toEqual({ kind: 'key-press', keycode: 'C_BRI_UP' });
  await page.reload();
  await navigateWorkspace(page, 'Keymap');
  await panel.getByRole('group', { name: 'Keymap layers' }).getByRole('button', { name: '1 Layer 1' }).click();
  await panel.getByRole('button', { name: 'Encoders', exact: true }).click();
  await expect(panel.getByLabel('SW1 clockwise keycode', { exact: true })).toHaveValue('C_BRI_UP');
  await panel.getByText('Push button', { exact: true }).click();
  await expect(panel.getByLabel('SW1 push behavior', { exact: true })).toHaveValue('layer-tap');
  const download = page.waitForEvent('download');
  await panel.getByRole('button', { name: 'Export ZMK source', exact: true }).click();
  const archive = unzipSync(await readFile((await (await download).path())!));
  const source = strFromU8(archive['config/boards/shields/boardstudio/boardstudio.keymap']);
  expect(source).toContain('&mt LSHIFT A');
  expect(source).toContain('sensor-bindings');
  expect(source).toContain('&lt 0 B');
  expect(source).toContain('&kp C_VOL_UP');
  expect(source).toContain('&kp C_BRI_UP');
});

test('a standalone encoder changes its press scan mode without changing rotary bindings', async ({ page }) => {
  await openKeymapFixture(page, true);
  await navigateWorkspace(page, 'Keymap');
  const panel = page.locator('.wb-keymap-panel');
  await panel.getByRole('button', {name:'Encoders',exact:true}).click();
  await panel.getByLabel('ENC1 clockwise behavior', {exact:true}).selectOption('key-press');
  await panel.getByLabel('ENC1 clockwise keycode', {exact:true}).fill('C_VOL_UP');
  await panel.getByLabel('ENC1 clockwise keycode', {exact:true}).press('Tab');
  await expect.poll(async () => (await readWorkspaceDocument(page)).keymap?.layers[0].sensors.encoder?.clockwise).toEqual({kind:'key-press',keycode:'C_VOL_UP'});
  const before = await readWorkspaceDocument(page);
  await navigateWorkspace(page, 'PCB');
  await page.getByRole('treeitem', {name:/ENC1/}).click();
  const scan = page.getByLabel('Press scan mode', {exact:true});
  await expect(scan).toHaveValue('direct');
  await expect(scan.locator('option[value="matrix"]')).toHaveAttribute('disabled', '');
  await scan.selectOption('unassigned');
  await expect.poll(async () => (await readWorkspaceDocument(page)).parts.find(part => part.id==='encoder')?.properties?.pressScanMode).toBe('unassigned');
  expect((await readWorkspaceDocument(page)).keymap).toEqual(before.keymap);
  await page.getByRole('button', {name:'Undo',exact:true}).click();
  await expect(scan).toHaveValue('direct');
  await page.getByRole('button', {name:'Redo',exact:true}).click();
  await expect(scan).toHaveValue('unassigned');
  await page.reload();
  await navigateWorkspace(page, 'PCB');
  await page.getByRole('treeitem', {name:/ENC1/}).click();
  await expect(scan).toHaveValue('unassigned');
  expect((await readWorkspaceDocument(page)).keymap).toEqual(before.keymap);
});
