import { expect, test, type Page } from '@playwright/test';
import { navigateWorkspace } from './workspace-navigation';

async function configureGaskets(page: Page) {
  await page.goto('/');
  await navigateWorkspace(page, 'Case');
  await page.getByRole('button', { name: 'Configure mechanical stack', exact: true }).click();
  await page.getByRole('combobox', { name: 'Mount style', exact: true }).selectOption('gasket');
  await expect(page.getByRole('button', { name: 'Export geometry', exact: true })).toBeEnabled({ timeout: 45_000 });
  await page.getByRole('button', { name:'Expand Gaskets',exact:true }).click();
}

test('case assembly tree groups gaskets and selects focused part inspectors', async ({ page }) => {
  test.setTimeout(90_000);
  await configureGaskets(page);
  const tree = page.getByRole('tree', { name: 'CAD structure' });
  await expect(tree.getByRole('button', { name: 'Expand PCB', exact: true })).toBeVisible();
  await expect(tree.getByRole('treeitem', { name: /^Gasket \d/ })).toHaveCount(6);
  await tree.getByRole('treeitem', { name: 'Plate', exact: true }).click();
  const panel = page.locator('.wb-mechanical-panel');
  await expect(panel.getByRole('heading', { name: 'Plate', exact: true })).toBeVisible();
  await expect(panel.getByRole('spinbutton', { name: 'Plate thickness mm', exact: true })).toBeVisible();
  await expect(panel.getByText('Closure hardware', { exact: true })).toHaveCount(0);
  await tree.getByRole('treeitem', { name: /^Gasket 1 / }).click();
  await expect(panel.getByRole('heading', { name: 'Gasket 1', exact: true })).toBeVisible();
  await expect(panel.getByRole('spinbutton', { name: 'Cut length mm', exact: true })).toBeVisible();
  await expect(panel.getByRole('spinbutton', { name: 'Plate thickness mm', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Edit gaskets', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await tree.getByRole('treeitem', { name: 'Plate', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Edit gaskets', exact: true })).toHaveAttribute('aria-pressed', 'false');
});

test('an invalid individual gasket stays saved and resizing repairs it with undo and redo', async ({ page }) => {
  test.setTimeout(90_000);
  await configureGaskets(page);
  const tree = page.getByRole('tree', { name: 'CAD structure' });
  await tree.getByRole('treeitem', { name: /^Gasket 1 / }).click();
  const length = page.getByRole('spinbutton', { name: 'Cut length mm', exact: true });
  const original = await length.inputValue();
  await length.fill('80');
  await length.press('Enter');
  await expect(page.locator('.wb-mech-error').first()).toContainText('Gasket');
  await expect(page.getByRole('button', { name: 'Export geometry', exact: true })).toBeDisabled();
  await expect(length).toHaveValue('80');
  await expect(tree.getByRole('treeitem', { name: /^Gasket 1 / })).toContainText('Does not fit');
  await expect(page.locator('.wb-save-state')).toHaveClass(/is-saved/);
  await page.reload();
  await navigateWorkspace(page, 'Case');
  await page.getByRole('button', { name:'Expand Gaskets',exact:true }).click();
  await tree.getByRole('treeitem', { name: /^Gasket 1 / }).click();
  await expect(length).toHaveValue('80');
  await length.fill(original);
  await length.press('Enter');
  await expect(page.getByRole('button', { name: 'Export geometry', exact: true })).toBeEnabled({ timeout: 45_000 });
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(length).toHaveValue('80');
  await expect(page.getByRole('button', { name: 'Export geometry', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect(length).toHaveValue(original);
  await expect(page.getByRole('button', { name: 'Export geometry', exact: true })).toBeEnabled({ timeout: 45_000 });
});

test('gasket material controls cancel edits and retain stock changes through reopen', async ({ page }) => {
  test.setTimeout(90_000);
  await configureGaskets(page);
  const group = page.getByRole('treeitem', { name: /^Gaskets / });
  await group.click();
  const thickness = page.getByRole('spinbutton', { name: 'Gasket thickness mm', exact: true });
  await thickness.fill('4');
  await thickness.press('Escape');
  await expect(thickness).toHaveValue('2');
  const stock = page.getByRole('combobox', { name: 'Foam stock', exact: true });
  await expect(stock.locator('option')).toHaveCount(14);
  await stock.selectOption('B2');
  await expect(page.getByRole('spinbutton', { name: 'Gasket width mm', exact: true })).toHaveValue('4');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(stock).toHaveValue('custom');
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect(stock).toHaveValue('B2');
  await expect(page.locator('.wb-save-state')).toHaveClass(/is-saved/);
  await page.reload();
  await navigateWorkspace(page, 'Case');
  await group.click();
  await expect(stock).toHaveValue('B2');
  await expect(page.getByRole('checkbox', { name: 'Fit cut lengths automatically on four sides', exact: true })).toBeChecked();
});

test('changing support count preserves adopted closures and invalid walls block export', async ({ page }) => {
  test.setTimeout(90_000);
  await configureGaskets(page);
  const panel = page.locator('.wb-mechanical-panel');
  await panel.locator('summary').filter({ hasText: 'Suggested mount locations' }).click();
  await page.getByRole('button', { name: 'Adopt closure positions', exact: true }).click();
  const closures = panel.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^Closure screws/ }) });
  const xs = closures.getByRole('spinbutton', { name: 'Position X mm', exact: true });
  const ys = closures.getByRole('spinbutton', { name: 'Position Y mm', exact: true });
  if (await closures.getAttribute('open') === null) await closures.locator('summary').first().click();
  await expect(xs).toHaveCount(4);
  const positions = await Promise.all([xs.evaluateAll(inputs => inputs.map(input => (input as HTMLInputElement).value)), ys.evaluateAll(inputs => inputs.map(input => (input as HTMLInputElement).value))]);
  await page.getByRole('treeitem', { name: /^Gaskets / }).click();
  const count = page.getByRole('spinbutton', { name: 'Supports per region', exact: true });
  await count.fill('5');
  await count.press('Enter');
  await expect(page.getByRole('button', { name: 'Export geometry', exact: true })).toBeEnabled({ timeout: 45_000 });
  await page.getByRole('button', { name: 'Assembly settings', exact: true }).click();
  if (await closures.getAttribute('open') === null) await closures.locator('summary').first().click();
  await expect(xs).toHaveCount(4);
  expect(await xs.evaluateAll(inputs => inputs.map(input => (input as HTMLInputElement).value))).toEqual(positions[0]);
  expect(await ys.evaluateAll(inputs => inputs.map(input => (input as HTMLInputElement).value))).toEqual(positions[1]);
  await page.getByRole('treeitem', { name: /^Gaskets / }).click();
  await panel.locator('summary').filter({ hasText: 'Advanced gasket clearances' }).click();
  const wall = panel.getByRole('spinbutton', { name: 'Minimum wall behind gasket pockets mm', exact: true });
  await wall.fill('3');
  await wall.press('Enter');
  await expect(page.getByText('Nominal wall is smaller than the minimum wall behind gasket pockets.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Export geometry', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(wall).toHaveValue('2');
  await expect(page.getByRole('button', { name: 'Export geometry', exact: true })).toBeEnabled({ timeout: 45_000 });
});

test('part display controls and adjustable assembly views do not regenerate geometry', async ({ page }) => {
  test.setTimeout(90_000);
  await configureGaskets(page);
  const status = page.locator('.wb-mechanical-preview-status');
  await expect(status).toContainText('Generated CAD solids');
  const revision = await status.textContent();
  const tree = page.getByRole('tree', { name:'CAD structure' });
  await expect(page.getByRole('combobox', { name:'Selected board', exact:true })).toHaveCount(0);
  await tree.getByRole('treeitem', { name:'Plate', exact:true }).click();
  await tree.getByRole('button', { name:'Hide Plate', exact:true }).click();
  await expect(page.getByRole('checkbox', { name:'Visible', exact:true })).not.toBeChecked();
  await tree.getByRole('button', { name:'Show Plate', exact:true }).click();
  await expect(page.getByRole('checkbox', { name:'Visible', exact:true })).toBeChecked();
  const canvas = page.locator('.wb-assembly-viewport canvas');
  const originalPixels = await canvas.screenshot();
  await page.getByLabel('Part colour', { exact:true }).fill('#ff7744');
  await expect.poll(async () => Buffer.compare(await canvas.screenshot(), originalPixels)).not.toBe(0);
  await page.screenshot({path:'test-results/case-colour.png'});
  await page.getByRole('button', { name:'Exploded', exact:true }).click();
  await page.getByRole('slider', { name:'Exploded separation', exact:true }).fill('4');
  await page.getByRole('button', { name:'Section', exact:true }).click();
  await page.getByRole('combobox', { name:'Section plane', exact:true }).selectOption('XY');
  await page.getByRole('slider', { name:'Section position', exact:true }).fill('30');
  await expect(page.getByRole('checkbox', { name:'Show plane', exact:true })).toBeChecked();
  await page.getByRole('button', { name:'Show hidden lines', exact:true }).click();
  await expect(page.getByRole('button', { name:'Show hidden lines', exact:true })).toHaveAttribute('aria-pressed','true');
  await expect(status).toHaveText(revision!);
  await page.reload();
  await navigateWorkspace(page, 'Case');
  await tree.getByRole('treeitem', { name:'Plate', exact:true }).click();
  await expect(page.getByLabel('Part colour', { exact:true })).toHaveValue('#ff7744');
});

test('split case selection generates each half with shared insert hardware', async ({ page }) => {
  test.setTimeout(120_000);
  await page.goto('/');
  await page.getByRole('button', {name:'Project',exact:true}).click();
  await page.getByRole('button', {name:'Start Sofle v2',exact:true}).click();
  await expect(page.locator('.wb-project-name')).toHaveText('Sofle v2');
  await navigateWorkspace(page,'Case');
  await page.getByRole('button', {name:'Configure mechanical stack',exact:true}).click();
  await page.getByRole('combobox', {name:'Mount style',exact:true}).selectOption('gasket');
  const tree = page.getByRole('tree', {name:'CAD structure'});
  const left = tree.getByRole('treeitem', {name:'Left case assembly',exact:true});
  const right = tree.getByRole('treeitem', {name:'Right case assembly',exact:true});
  await expect(left).toHaveAttribute('aria-selected','true');
  await expect(right).toBeVisible();
  const inserts = page.getByRole('combobox', {name:'Insert size',exact:true});
  await expect(inserts).toHaveValue('m2-3');
  await expect(page.getByRole('button', {name:'Export geometry',exact:true})).toBeEnabled({timeout:45_000});
  await inserts.selectOption('m2-4');
  await right.click();
  await expect(right).toHaveAttribute('aria-selected','true');
  await expect(inserts).toHaveValue('m2-4');
  await expect(page.getByRole('button', {name:'Export geometry',exact:true})).toBeEnabled({timeout:45_000});
  await inserts.selectOption('m2-3');
  await left.click();
  await expect(inserts).toHaveValue('m2-3');
  await expect(page.getByRole('button', {name:'Export geometry',exact:true})).toBeEnabled({timeout:45_000});
  await tree.getByRole('treeitem', {name:'Top case',exact:true}).click();
  await expect(inserts).toHaveCount(0);
  await expect(page.getByRole('button', {name:'Edit shared closure hardware',exact:true})).toBeVisible();
});

test('Sofle chooses more than four supports and manual count survives reopening', async ({ page }) => {
  test.setTimeout(120_000);
  await page.goto('/');
  await page.getByRole('button', {name:'Project',exact:true}).click();
  await page.getByRole('button', {name:'Start Sofle v2',exact:true}).click();
  await expect(page.locator('.wb-project-name')).toHaveText('Sofle v2');
  await navigateWorkspace(page,'Case');
  await page.getByRole('button', {name:'Configure mechanical stack',exact:true}).click();
  await page.getByRole('combobox', {name:'Mount style',exact:true}).selectOption('gasket');
  await expect(page.getByRole('button', {name:'Export geometry',exact:true})).toBeEnabled({timeout:45_000});
  await page.getByRole('treeitem', {name:/^Gaskets /}).click();
  const automatic = page.getByRole('checkbox', {name:'Choose support count automatically',exact:true});
  const count = page.getByRole('spinbutton', {name:'Supports per region',exact:true});
  await expect(automatic).toBeChecked();
  const chosen = Number(await count.inputValue());
  expect(chosen).toBeGreaterThan(4);
  await page.setViewportSize({width:1600,height:1100});
  const editGaskets = page.getByRole('button', {name:'Edit gaskets',exact:true});
  if (await editGaskets.getAttribute('aria-pressed') !== 'true') await editGaskets.click();
  await expect(editGaskets).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button', {name:'Top',exact:true}).click();
  await page.locator('.wb-assembly-viewport').screenshot({path:'test-results/sofle-run-placement.png'});
  const manual = String(chosen - 4);
  await count.fill(manual); await count.press('Enter');
  await expect(automatic).not.toBeChecked();
  await expect(page.getByRole('treeitem', {name:/^Gaskets /})).toContainText(`${manual} pairs`);
  await expect(page.getByRole('button', {name:'Export geometry',exact:true})).toBeEnabled({timeout:45_000});
  await expect(page.locator('.wb-save-state')).toHaveClass(/is-saved/);
  await page.reload();
  await expect(page.locator('.wb-project-name')).toHaveText('Sofle v2');
  await navigateWorkspace(page,'Case');
  await page.getByRole('treeitem', {name:/^Gaskets /}).click();
  await expect(count).toHaveValue(manual);
  await expect(automatic).not.toBeChecked();
  await automatic.check();
  await expect(count).toHaveValue(String(chosen));
});
