import { expect, test } from '@playwright/test';
import type { ModuleDefinition } from '@boardstudio/v2-contracts';
import { readFile } from 'node:fs/promises';
import { demoProject } from '../src/demo';
import { openWorkspaceDocument, readWorkspaceDocument } from './workspace-storage';
import { navigateWorkspace } from './workspace-navigation';

test('a module case collision highlights only the intersecting material', async ({ page }) => {
  const document = demoProject();
  document.id = 'module-case-findings';
  document.parts = []; document.definitions = []; document.nets = [];
  document.matrices = []; document.layouts = []; document.caseBodies = [];
  document.hardware = undefined;
  const board = document.boards[0];
  document.boards = [{...board, partIds:[], netIds:[], outlineIds:['boundary']}];
  document.outline = [{kind:'rect',id:'boundary',center:{x:0,y:0},size:{x:80,y:80},radius:0,operation:'add'}];
  const catalogue = JSON.parse(await readFile(new URL('../src/modules/imported-modules.json', import.meta.url), 'utf8')) as {modules: {row:string;definition:ModuleDefinition}[]};
  const definition = catalogue.modules.find(entry => entry.row === 'vik-splitter')!.definition;
  document.moduleDefinitions = [definition];
  document.modules = [{id:'mounted',definitionId:definition.id,hostBoardId:board.id,hostFace:'back',facingFace:'back',at:{x:27,y:0},rotation:0,gap:3,attachment:'board',detached:false,serviceClearance:1}];
  document.mechanical = {boardId:board.id,method:'printed',mount:'rigid',integratedPlateFrame:false,bottomStyle:'shell',plateThickness:1.5,plateFoamThickness:0,pcbThickness:1.6,bottomFoamThickness:0,batteryHeight:0,bottomThickness:2,plateToPcb:3.5,wallThickness:2,clearance:0.2,profiles:[],mounts:[]};
  await openWorkspaceDocument(page, document);
  await navigateWorkspace(page, 'Case');
  await expect.poll(async () => (await readWorkspaceDocument(page)).id).toBe(document.id);
  const saved = await readWorkspaceDocument(page);
  expect(saved.parts).toHaveLength(0);
  expect(saved.modules).toEqual(document.modules);
  await expect.poll(async () => page.getByText(`Configuration resolved · r${(await readWorkspaceDocument(page)).revision}`, {exact:true}).count()).toBe(1);
  const failure = page.locator('.wb-findings li').filter({hasText:/Module clearance intersects solid/}).first();
  await expect(failure).toBeVisible();
  await failure.getByRole('button', {name:'Select affected geometry',exact:true}).click();
  const marker = page.locator('.wb-outline-finding.is-focused');
  await expect(marker).toBeVisible();
  await expect(marker.locator('polygon').first()).toBeVisible();
  const points = await marker.locator('polygon').evaluateAll(nodes => nodes.flatMap(node => (node.getAttribute('points') ?? '').split(/\s+/).filter(Boolean).map(pair => pair.split(',').map(Number))));
  expect(points.length).toBeGreaterThan(2);
  expect(points.every(point => point[0] > 39.5)).toBe(true);
  expect(Math.max(...points.map(point => point[0])) - Math.min(...points.map(point => point[0]))).toBeLessThan(1);
  await page.getByRole('button', {name:'Fit board',exact:true}).click();
  await expect(marker.locator('polygon').first()).toBeVisible();
});
