import { expect, test } from '@playwright/test';
import { openKeymapFixture } from './keymap-fixture';
import { navigateWorkspace } from './workspace-navigation';
import { readWorkspaceDocument } from './workspace-storage';

test('VIK source variants mount below a PCB and create independent editable circuits', async ({ page }) => {
  await openKeymapFixture(page);
  await navigateWorkspace(page, 'Parts');
  const modules = page.getByRole('listbox', { name: 'VIK modules', exact: true });
  await expect(modules.getByRole('option')).toHaveCount(29);
  await modules.getByRole('option', { name: /DRV2605L/u }).click();
  const variant = page.getByLabel('Module variant', { exact: true });
  const repaired = await variant.locator('option').filter({ hasText: '3V3 pullups' }).getAttribute('value');
  await variant.selectOption(repaired!);
  await page.getByLabel('Module host face', { exact: true }).selectOption('back');
  await page.getByLabel('Module surface gap', { exact: true }).fill('4');
  await page.getByLabel('Module surface gap', { exact: true }).press('Tab');
  await page.getByRole('button', { name: 'Attach module', exact: true }).click();
  await expect.poll(async () => (await readWorkspaceDocument(page)).modules?.length).toBe(1);
  const saved = await readWorkspaceDocument(page);
  expect(saved.modules?.[0]).toMatchObject({hostFace:'back',facingFace:'back',gap:4});
  expect(saved.moduleDefinitions?.[0].circuit?.adaptations.length).toBeGreaterThan(0);
  await page.getByRole('button', {name:'Undo',exact:true}).click();
  await expect.poll(async () => (await readWorkspaceDocument(page)).modules?.length ?? 0).toBe(0);
  await page.getByRole('button', {name:'Redo',exact:true}).click();
  await expect.poll(async () => (await readWorkspaceDocument(page)).modules?.length).toBe(1);
  await page.getByLabel('Module surface gap', {exact:true}).fill('6');
  await page.getByLabel('Module surface gap', {exact:true}).press('Tab');
  await page.getByRole('button', {name:'Save placement',exact:true}).click();
  await expect.poll(async () => (await readWorkspaceDocument(page)).modules?.[0].gap).toBe(6);
  await page.getByRole('button', {name:'Undo',exact:true}).click();
  await expect.poll(async () => (await readWorkspaceDocument(page)).modules?.[0].gap).toBe(4);
  await expect(page.getByLabel('Module surface gap', {exact:true})).toHaveValue('4');
  await page.getByText('Assembly geometry', {exact:true}).click();
  for (const [field, value] of [['width','2'],['depth','3'],['z','1'],['height','4'],['evidence','Measured fixture']] as const) {
    await page.getByLabel(`Module volume ${field}`, {exact:true}).fill(value);
    await page.getByLabel(`Module volume ${field}`, {exact:true}).press('Tab');
  }
  await page.getByRole('button', {name:'Add measured volume',exact:true}).click();
  await expect(page.getByText('occupied · 4 mm · Unreviewed', {exact:true})).toBeVisible();
  await page.getByLabel('Module surface gap', {exact:true}).fill('5');
  await page.getByLabel('Module surface gap', {exact:true}).press('Tab');
  await page.getByRole('button', {name:'Save placement',exact:true}).click();
  await expect.poll(async () => (await readWorkspaceDocument(page)).modules?.[0].gap).toBe(5);
  await expect(page.getByText('occupied · 4 mm · Unreviewed', {exact:true})).toBeVisible();
  await page.getByText('Use circuit on PCB', {exact:true}).click();
  await page.getByRole('button', {name:'Copy circuit to PCB',exact:true}).click();
  await expect.poll(async () => (await readWorkspaceDocument(page)).embeddedCircuits?.length).toBe(1);
  const embedded = await readWorkspaceDocument(page);
  const group = embedded.embeddedCircuits![0];
  expect(group.partIds.length).toBeGreaterThan(10);
  const vdd = embedded.nets.find(net => net.name === '+3V3' && net.id.startsWith(`embedded/${group.id}/`));
  expect(vdd?.pins.some(pin => pin.partId.endsWith('/R1'))).toBe(true);
  await page.reload();
  await expect.poll(async () => (await readWorkspaceDocument(page)).modules?.length).toBe(1);
  await expect.poll(async () => (await readWorkspaceDocument(page)).embeddedCircuits?.length).toBe(1);
});
