[package]
name = "boardstudio-application"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
boardstudio_core = { path = "../core" }

[dev-dependencies]
boardstudio_core = { path = "../core" }

[lib]
name = "boardstudio_application"
path = "src/lib.rs"

[lints]
workspace = true
