#!/usr/bin/env python3
"""Read and update frontend delivery records without copying their evidence."""

import argparse
from collections import Counter
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
RUN = Path("docs/migration/dioxus-frontend-v1-run.json")
TASKS = Path(".scratch/dioxus-frontend-v1/tasks.json")
RF = Path(".scratch/dioxus-frontend-v1/refactor-findings.json")
REPORT = Path("docs/migration/POST-PORT-REFACTOR.md")


def read(path):
    return json.loads((ROOT / path).read_text())


def write(path, value):
    target = ROOT / path
    content = json.dumps(value, indent=2) + "\n"
    if target.read_text() != content:
        target.write_text(content)


def counts(tasks):
    return dict(Counter(task["status"] for task in tasks)) | {"total": len(tasks)}


def refactor_report():
    ledger = read(RF)
    lines = [
        "# Post-port refactoring takeaways", "",
        "Generated by `python3 .scratch/dioxus-frontend-v1/progress.py sync` from the "
        "[RF ledger](../../.scratch/dioxus-frontend-v1/refactor-findings.json). "
        "Edit that ledger; this report is a derived view.", "",
        "All stable RF IDs and detailed source observations remain in the ledger. "
        "The [earlier narrative](history/POST-PORT-REFACTOR-before-20261003-streamline.md) "
        "is retained as history. Required parity fixes remain current work; "
        "structural proposals belong to the later refactoring phase.", "",
    ]
    for finding in ledger["findings"]:
        lines += [f"## {finding['id']}: {finding['title']}", ""]
        for field, label in (
            ("status", "Status"), ("confidence", "Confidence"),
            ("observation", "Observation"), ("impact", "Impact"),
            ("during_port", "Current mitigation"),
            ("post_port_proposal", "Later proposal"),
            ("validation_needed", "Validation"),
        ):
            if finding.get(field):
                lines += [f"**{label}:** {finding[field]}", ""]
        evidence = finding.get("evidence", [])
        if evidence:
            lines += ["**Evidence:** " + "; ".join(f"`{item}`" for item in evidence), ""]
        observations = finding.get("handoff_evidence", [])
        if observations:
            lines += [f"{len(observations)} additional source observations are indexed "
                      "under this RF ID in the ledger.", ""]
    return "\n".join(lines)


def validate(run, graph):
    tasks = graph["tasks"]
    ids = {task["id"] for task in tasks}
    if len(ids) != len(tasks) or len(tasks) != 62:
        raise ValueError("The 62 canonical parents must remain unique and intact")
    expected = counts(tasks)
    if run["current_progress"]["parent_counts"] != expected:
        raise ValueError("Derived parent counts are stale; run sync")
    if graph["counts"]["status"] != {k: v for k, v in expected.items() if k != "total"}:
        raise ValueError("Task count cache is stale; run sync")
    for task in tasks:
        if any(join not in ids for join in task["depends_on"]):
            raise ValueError(f"Unknown parent dependency for {task['id']}")
    findings = read(RF)["findings"]
    if len({finding["id"] for finding in findings}) != len(findings):
        raise ValueError("Duplicate RF ID")


def set_status(graph, args):
    tasks = {task["id"]: task for task in graph["tasks"]}
    task = tasks[args.parent]
    previous = task["status"]
    if previous == args.status:
        return
    if previous == "accepted":
        raise ValueError("Accepted parents need an explicit correction decision")
    transition = {"at": datetime.now(timezone.utc).isoformat(),
                  "from": previous, "to": args.status, "reason": args.reason}
    if args.status == "accepted":
        if not args.decision:
            raise ValueError("Acceptance requires a finalized decision record")
        decision_path = Path(args.decision)
        if decision_path.is_absolute() or ".." in decision_path.parts:
            raise ValueError("Use a repository-relative decision path")
        decision = read(decision_path)
        if decision["parent"] != args.parent:
            raise ValueError("Decision names a different parent")
        for join in task["acceptance_after"]:
            if tasks[join]["status"] != "accepted":
                raise ValueError(f"Unmet final acceptance join: {join}")
        for key in ("review", "audit"):
            evidence = ROOT / decision[key]
            if hashlib.sha256(evidence.read_bytes()).hexdigest() != decision[key + "_sha256"]:
                raise ValueError(f"Finalized {key} hash mismatch")
        if not (ROOT / decision["criteria_accounting"]).is_file():
            raise ValueError("Missing criterion accounting")
        transition["decision"] = str(decision_path)
        # The decision owns the scope, hashes and verdict. Keep only its reference here.
        task["completion_evidence"] = {"decision_record": str(decision_path)}
    task["status"] = args.status
    task.setdefault("status_history", []).append(transition)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    show = commands.add_parser("show", help="Read current candidate, derived parent counts and six queues")
    show.add_argument("--json", action="store_true")
    commands.add_parser("check", help="Check record consistency without running application tests")
    commands.add_parser("sync", help="Refresh derived counts and the readable RF report")
    status = commands.add_parser("set-status", help="Coordinator-only parent transition and derived refresh")
    status.add_argument("parent")
    status.add_argument("status", choices=("planned", "implementing", "accepted"))
    status.add_argument("--reason", required=True)
    status.add_argument("--decision")
    args = parser.parse_args()
    run, graph = read(RUN), read(TASKS)
    if args.command == "set-status":
        set_status(graph, args)
    if args.command in ("sync", "set-status"):
        parent_counts = counts(graph["tasks"])
        graph["counts"]["status"] = {k: v for k, v in parent_counts.items() if k != "total"}
        run["current_progress"]["parent_counts"] = parent_counts
        run["current_progress"]["updated_at"] = datetime.now(timezone.utc).isoformat()
        validate(run, graph)
        write(TASKS, graph)
        write(RUN, run)
        (ROOT / REPORT).write_text(refactor_report())
    elif args.command == "check":
        validate(run, graph)
        if (ROOT / REPORT).read_text() != refactor_report():
            raise ValueError("Derived RF report is stale; run sync")
        print("Progress, 62 parents and RF report are consistent")
        return
    progress = run["current_progress"]
    if args.command == "show" and args.json:
        print(json.dumps(progress | {"parent_counts": counts(graph["tasks"])}, indent=2))
        return
    tally = counts(graph["tasks"])
    print(f"Parents: {tally.get('accepted', 0)}/{tally['total']} accepted; "
          f"{tally.get('implementing', 0)} implementing; {tally.get('planned', 0)} planned")
    candidate = progress["served_candidate"]
    print(f"Served: {candidate['root_url']} ({candidate['source_commit'][:8]})")
    print(f"Integration: {progress['integration']['state']}")
    for stream in progress["active_streams"]:
        print(f"{stream['stream']}: {stream['state']}")


if __name__ == "__main__":
    try:
        main()
    except (KeyError, ValueError, OSError) as error:
        print(f"Progress record error: {error}", file=sys.stderr)
        sys.exit(1)
