import { navigateWorkspace } from '../e2e/workspace-navigation';
import { expect, test } from '@playwright/test';

test('Pages subpath loads workers, CAD, models and offline exports', async ({ page, context }) => {
  test.setTimeout(90_000);
  const failed: string[] = [];
  const wasmRequests: string[] = [];
  page.on('response', (response) => {
    if (response.status() >= 400) failed.push(`${response.status()} ${response.url()}`);
    if (/\.wasm(?:$|\?)/i.test(response.url())) wasmRequests.push(response.url());
  });
  await page.goto('./');
  await expect(page.locator('.wb-outline-shape')).toHaveCount(1);
  expect(wasmRequests.some((url) => /boardstudio_renderer_wasm_bg/i.test(url))).toBe(false);
  await page.getByRole('tab', { name: 'Parts', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Search footprints' }).fill('ceoloide/switch_mx');
  await page.getByRole('option', { name: 'MX switch', exact: true }).click();
  await page.getByRole('checkbox', { name: 'hotswap', exact: true }).check();
  await page.getByRole('button', { name: '3D model', exact: true }).click();
  await expect(page.getByText('2 / 2 models · 1.6 mm PCB', { exact: true })).toBeVisible({ timeout: 45_000 });
  expect(wasmRequests.some((url) => /boardstudio_renderer_wasm_bg/i.test(url) && new URL(url).pathname.startsWith('/boardstudio/'))).toBe(true);
  await navigateWorkspace(page, 'Layout');
  const wasmBeforeCad = wasmRequests.length;
  await navigateWorkspace(page, 'Case');
  await page.getByRole('button', { name: 'Update preview', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Case generation' }).getByRole('status')).toHaveText('Preview current', { timeout: 45_000 });
  await expect.poll(() => wasmRequests.length).toBeGreaterThan(wasmBeforeCad);
  expect(wasmRequests.some((url) => /cadrum/i.test(url) && new URL(url).pathname.startsWith('/boardstudio/'))).toBe(true);
  const scope = await page.evaluate(async () => (await navigator.serviceWorker.ready).scope);
  expect(new URL(scope).pathname).toBe('/boardstudio/');
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true);
  await context.setOffline(true);
  await page.reload();
  await expect(page.locator('.wb-outline-shape')).toHaveCount(1);
  await navigateWorkspace(page, 'Case');
  await page.getByRole('button', { name: 'Update preview', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Case generation' }).getByRole('status')).toHaveText('Preview current', { timeout: 45_000 });
  await page.locator('.wb-topbar').getByRole('button', { name: 'Export', exact: true }).click();
  const download = page.waitForEvent('download');
  await page.locator('.wb-export-row').filter({ hasText: 'Case STEP' }).getByRole('button', { name: 'Export' }).click();
  expect((await download).suggestedFilename()).toBe('Starter keyboard-case.step');
  expect(failed).toEqual([]);
});
